version: "3"

services:

  mysqlDevChallenge:
    image: mysql:8.0.2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devChallenge
    volumes:
      - "./dataMySql:/var/lib/mysql:rw" 
    ports:
      - "3308:3306"
    command: "--innodb_use_native_aio=0"

  postGDevChallenge:
    image: postgres
    environment: 
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: devChallenge
    volumes:
      - "./dataPostGres:/var/lib/postgresql:rw" 
    ports:
      - "5432:5432"

  admin: #http://192.168.99.100:8080/ 
    image: adminer
    ports:
      - 8080:8080
